### ISSUE TITLE
[Bug]: Monsters only up to Legendary* are spawning.

### ISSUE THREAD

**Issue by GlitchPenguin** [dr3ams/Roguelike-Adventures-and-Dungeons-2#313]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the modpack

### Your launcher

CurseForge

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.3

### Describe your issue

I haven't seen a single ultimate monster, even though I have killed both the Wither and the Ender Dragon.

### Steps to reproduce the issue

1. Kill Ender Dragon before Wither
2. Progression ruined?

### Additional Information

[00:02:07] [main/WARN]: Received passengers for unknown entity
[00:04:03] [main/INFO]: [Town Tourist]
[00:04:03] [main/ERROR]: Exception caught during firing event: Non [a-z0-9/._-] character in path of location: betterdungeons:town _tourist
	Index: 4
	Listeners:
		0: HIGH
		1: ASM: class me.shedaniel.architectury.event.forge.EventHandlerImplClient event(Lnet/minecraftforge/client/event/ClientChatReceivedEvent;)V
		2: NORMAL
		3: ASM: xaero.common.events.ForgeEventHandler@3aba36ff handleClientChatReceivedEvent(Lnet/minecraftforge/client/event/ClientChatReceivedEvent;)V
		4: ASM: class aurilux.titles.client.handler.ClientEventHandler onClientReceivedChat(Lnet/minecraftforge/client/event/ClientChatReceivedEvent;)V
		5: net.minecraftforge.eventbus.EventBus$$Lambda$2919/1643298618@734dd903
net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: betterdungeons:town _tourist
	at net.minecraft.util.ResourceLocation.<init>(ResourceLocation.java:33)
	at net.minecraft.util.ResourceLocation.<init>(ResourceLocation.java:38)
	at aurilux.titles.client.handler.ClientEventHandler.processKey(ClientEventHandler.java:119)
	at aurilux.titles.client.handler.ClientEventHandler.onClientReceivedChat(ClientEventHandler.java:59)
	at net.minecraftforge.eventbus.ASMEventHandler_1227_ClientEventHandler_onClientReceivedChat_ClientChatReceivedEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus$$Lambda$3288/1423450988.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.event.ForgeEventFactory.onClientChat(ForgeEventFactory.java:344)
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147251_a(ClientPlayNetHandler.java:820)
	at net.minecraft.network.play.server.SChatPacket.func_148833_a(SourceFile:41)
	at net.minecraft.network.play.server.SChatPacket.func_148833_a(SourceFile:11)
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21)
	at net.minecraft.network.PacketThreadUtil$$Lambda$29484/1525415678.run(Unknown Source)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:948)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$496/1552617652.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)

[00:04:03] [main/FATAL]: Error executing task on Client
net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: betterdungeons:town _tourist
	at net.minecraft.util.ResourceLocation.<init>(ResourceLocation.java:33) ~[?:?]
	at net.minecraft.util.ResourceLocation.<init>(ResourceLocation.java:38) ~[?:?]
	at aurilux.titles.client.handler.ClientEventHandler.processKey(ClientEventHandler.java:119) ~[?:Titles-1.16.5-3.4.4.jar]
	at aurilux.titles.client.handler.ClientEventHandler.onClientReceivedChat(ClientEventHandler.java:59) ~[?:Titles-1.16.5-3.4.4.jar]
	at net.minecraftforge.eventbus.ASMEventHandler_1227_ClientEventHandler_onClientReceivedChat_ClientChatReceivedEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$3288/1423450988.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.event.ForgeEventFactory.onClientChat(ForgeEventFactory.java:344) ~[?:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147251_a(ClientPlayNetHandler.java:820) ~[?:?]
	at net.minecraft.network.play.server.SChatPacket.func_148833_a(SourceFile:41) ~[?:?]
	at net.minecraft.network.play.server.SChatPacket.func_148833_a(SourceFile:11) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$29484/1525415678.run(Unknown Source) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:948) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) [forge-1.16.5-36.2.39.jar:36.2]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$496/1552617652.call(Unknown Source) [forge-1.16.5-36.2.39.jar:36.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?]
[00:04:03] [main/INFO]: Loaded 5374 advancements
[00:04:05] [main/ERROR]: Received invalid update packet for null tile entity at BlockPos{x=-1365, y=67, z=9283} with data: {LootTable:"minecraft:chests/village/village_snowy_house",specialLootChest_table:"minecraft:chests/village/village_snowy_house",specialLootChest_seed:1492245744109370448L,tileId:[I;415978216,-1937358125,-1322077682,233906644],LootrOpeners:[],x:-1365,y:67,ForgeCaps:{"improvedmobs:opened_flag":{HasBeenOpened:0b}},z:9283,id:"lootr:special_loot_chest",LootTableSeed:1492245744109370448L}
[00:04:18] [main/WARN]: Received passengers for unknown entity
[00:04:28] [main/INFO]: [CHAT] Activated Waystone: Mrokaires
[00:04:34] [main/INFO]: [CHAT] Activated Waystone: Zurzermur
[00:04:48] [main/WARN]: Received balloons for unknown entity!
[00:06:45] [main/WARN]: Received balloons for unknown entity!
[00:07:08] [main/INFO]: [CHAT] You Found 3 Iron Nugget Treasure!
[00:07:14] [main/INFO]: [CHAT] You Found 1 Iron Nugget Treasure!
[00:09:03] [main/WARN]: Received balloons for unknown entity!
[00:09:03] [main/WARN]: Received balloons for unknown entity!
[00:09:06] [main/INFO]: [CHAT] You Found 1 Iron Nugget Treasure!
[00:09:23] [main/WARN]: Received balloons for unknown entity!
[00:09:44] [main/WARN]: Received balloons for unknown entity!
[00:12:39] [main/WARN]: Received balloons for unknown entity!
[00:13:44] [main/WARN]: Received balloons for unknown entity!
[00:14:25] [main/INFO]: [CHAT] You Found 3 Iron Nugget Treasure!
[00:14:33] [main/WARN]: Received balloons for unknown entity!
[00:14:34] [main/WARN]: Received balloons for unknown entity!
[00:14:36] [main/WARN]: Received balloons for unknown entity!
[00:14:41] [main/INFO]: [CHAT] You Found 1 Iron Nugget Treasure!
[00:16:13] [main/INFO]: Villager VillagerEntity['Villager'/710140, l='ClientLevel', x=-793.63, y=69.56, z=9940.72] died, message: 'Villager died'
[00:22:46] [main/WARN]: Received passengers for unknown entity
[00:22:47] [main/WARN]: Received balloons for unknown entity!
[00:25:11] [main/WARN]: Received balloons for unknown entity!
[00:25:39] [main/WARN]: Received balloons for unknown entity!
[00:30:13] [main/INFO]: [CHAT] 16 Excavation level up!
[00:30:21] [main/INFO]: [CHAT] You Found 1 Iron Nugget Treasure!
[00:34:22] [main/INFO]: [net.minecraft.entity.LivingEntity:redirect$ble000$blue_skies$breakSoundModifier:8334]: falsite burger

**Comment by Zarchyar** [comment]
Good possibility you've just had "bad" luck the highest end champions are rather rare.

**Comment by Zarchyar** [comment]
The script factors in someone killing the dragon first actually you can get the first stage by simply entering the end 
The script will also add the wither stage on login to any player who has the ender dragon stage as an extra failsafe.

**Comment by Zarchyar** [comment]
If you want to check you have both the wither and enderdragon stages try the following command
/gamestage info (player)

**Comment by GlitchPenguin** [comment]
> Good possibility you've just had "bad" luck the highest end champions are rather rare.

I am pretty unlucky lol,

**Comment by GlitchPenguin** [comment]
My bad I'm new to GitHub I didn't realize I was closing a reopening the thread when I pressed that button 🤦‍♂️
