### ISSUE TITLE
Server launching issue

### ISSUE THREAD

**Issue by Mincrafter123** [dr3ams/Roguelike-Adventures-and-Dungeons-2#335]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [x] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [x] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.6

### Describe your issue

Server launch issues.  I'm trying to start a server however upon downloading the server pack. Each time I try to start it the following error appears and I cant seem to figure it out.

### Additional Information

Hi everyone!

I'm trying to start a server however upon downloading the server pack. Each time I try to start it the following error appears and I cant seem to figure it out.

 Crash Report UUID: 565c3436-5fd7-4cd2-9756-9a9ba78711d0[16:59:08] [main/FATAL] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Project MMO (pmmo) has failed to load correctly
?7java.lang.IncompatibleClassChangeError: Method 'dev.ftb.mods.ftbquests.quest.task.TaskType dev.ftb.mods.ftbquests.quest.task.TaskTypes.register(net.minecraft.util.ResourceLocation, dev.ftb.mods.ftbquests.quest.task.TaskType$Provider, java.util.function.Supplier)' must be InterfaceMethodref constant
]
        at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:255) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:222) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:180) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:30) ~[forge:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading,re:mixin,pl:mixin:A}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?] {}
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?] {}
        at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:37) ~[forge-1.16.5-36.2.39.jar:36.2] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {re:classloading}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {re:classloading}
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:49) [forge-1.16.5-36.2.39.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:46) [forge-1.16.5-36.2.39.jar:?] {}
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:43) [forge-1.16.5-36.2.39.jar:?] {}

Thank you very much for any help.

[crash-2023-08-23_16.59.08-fml.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/12416209/crash-2023-08-23_16.59.08-fml.txt)

**Comment by DoctorMage** [comment]
https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/issues/58
