### ISSUE TITLE
[Bug]: Server unable to start:  Project MMO (pmmo) has failed to load correctly

### ISSUE THREAD

**Issue by liamoshaughn** [dr3ams/Roguelike-Adventures-and-Dungeons-2#49]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

 sudo java -Xmx4G -jar forge-1.16.5-36.2.33.jar nogui

### Modpack version

0.7

### Describe your issue

Attempting to launch server comes out with a fatal error between FTBQuest and Project MMO

Error:
`[08:02:08] [main/FATAL] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Project MMO (pmmo) has failed to load correctly
§7java.lang.IncompatibleClassChangeError: Method 'dev.ftb.mods.ftbquests.quest.task.TaskType dev.ftb.mods.ftbquests.quest.task.TaskTypes.register(net.minecraft.util.ResourceLocation, dev.ftb.mods.ftbquests.quest.task.TaskType$Provider, java.util.function.Supplier)' must be InterfaceMethodref constant
]
        at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:269) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:236) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:194) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44) ~[forge:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading,re:mixin,pl:mixin:A}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?] {}
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?] {}
        at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.5-36.2.33.jar:36.2] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {re:classloading}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {re:classloading}
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.5-36.2.33.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.5-36.2.33.jar:?] {}
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.5-36.2.33.jar:?] {}`

### Steps to reproduce the issue

Run:  sudo java -Xmx4G -jar forge-1.16.5-36.2.33.jar nogui

### Additional Information

Using Debian cli
OpenJDK-11

**Comment by liamoshaughn** [comment]
Turns out it was because I was using jdk11 painstakingly installed jdk8 and it got to spawn area
